version: '3.8'

services:
  zookeeper1:
    image: zookeeper:3.8.4
    container_name: zookeeper1
    hostname: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - zk1_data:/data
      - zk1_datalog:/datalog

  zookeeper2:
    image: zookeeper:3.8.4
    container_name: zookeeper2
    hostname: zookeeper2
    ports:
      - "2182:2181" # Mapuj na inny port hosta, jeśli uruchamiasz wszystko na jednej maszynie
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - zk2_data:/data
      - zk2_datalog:/datalog
    depends_on:
      - zookeeper1

  zookeeper3:
    image: zookeeper:3.8.4
    container_name: zookeeper3
    hostname: zookeeper3
    ports:
      - "2183:2181" # Mapuj na inny port hosta
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - zk3_data:/data
      - zk3_datalog:/datalog
    depends_on:
      - zookeeper1
      - zookeeper2

volumes:
  zk1_data:
  zk1_datalog:
  zk2_data:
  zk2_datalog:
  zk3_data:
  zk3_datalog: